/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopperRouteImport } from './routes/shopper'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EditsRouteImport } from './routes/edits'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopperIndexRouteImport } from './routes/shopper.index'
import { Route as EditsIndexRouteImport } from './routes/edits.index'
import { Route as ShopperNewRouteImport } from './routes/shopper.new'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as EditsIdRouteImport } from './routes/edits.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopperRoute = ShopperRouteImport.update({
  id: '/shopper',
  path: '/shopper',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EditsRoute = EditsRouteImport.update({
  id: '/edits',
  path: '/edits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopperIndexRoute = ShopperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopperRoute,
} as any)
const EditsIndexRoute = EditsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditsRoute,
} as any)
const ShopperNewRoute = ShopperNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShopperRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const EditsIdRoute = EditsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/edits': typeof EditsRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shopper': typeof ShopperRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/edits/$id': typeof EditsIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shopper/new': typeof ShopperNewRoute
  '/edits/': typeof EditsIndexRoute
  '/shopper/': typeof ShopperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/edits/$id': typeof EditsIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shopper/new': typeof ShopperNewRoute
  '/edits': typeof EditsIndexRoute
  '/shopper': typeof ShopperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/edits': typeof EditsRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shopper': typeof ShopperRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/edits/$id': typeof EditsIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shopper/new': typeof ShopperNewRoute
  '/edits/': typeof EditsIndexRoute
  '/shopper/': typeof ShopperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/edits'
    | '/search'
    | '/shop'
    | '/shopper'
    | '/wishlist'
    | '/edits/$id'
    | '/product/$handle'
    | '/shopper/new'
    | '/edits/'
    | '/shopper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/search'
    | '/shop'
    | '/wishlist'
    | '/edits/$id'
    | '/product/$handle'
    | '/shopper/new'
    | '/edits'
    | '/shopper'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/edits'
    | '/search'
    | '/shop'
    | '/shopper'
    | '/wishlist'
    | '/edits/$id'
    | '/product/$handle'
    | '/shopper/new'
    | '/edits/'
    | '/shopper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  EditsRoute: typeof EditsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  ShopperRoute: typeof ShopperRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopper': {
      id: '/shopper'
      path: '/shopper'
      fullPath: '/shopper'
      preLoaderRoute: typeof ShopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edits': {
      id: '/edits'
      path: '/edits'
      fullPath: '/edits'
      preLoaderRoute: typeof EditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopper/': {
      id: '/shopper/'
      path: '/'
      fullPath: '/shopper/'
      preLoaderRoute: typeof ShopperIndexRouteImport
      parentRoute: typeof ShopperRoute
    }
    '/edits/': {
      id: '/edits/'
      path: '/'
      fullPath: '/edits/'
      preLoaderRoute: typeof EditsIndexRouteImport
      parentRoute: typeof EditsRoute
    }
    '/shopper/new': {
      id: '/shopper/new'
      path: '/new'
      fullPath: '/shopper/new'
      preLoaderRoute: typeof ShopperNewRouteImport
      parentRoute: typeof ShopperRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edits/$id': {
      id: '/edits/$id'
      path: '/$id'
      fullPath: '/edits/$id'
      preLoaderRoute: typeof EditsIdRouteImport
      parentRoute: typeof EditsRoute
    }
  }
}

interface EditsRouteChildren {
  EditsIdRoute: typeof EditsIdRoute
  EditsIndexRoute: typeof EditsIndexRoute
}

const EditsRouteChildren: EditsRouteChildren = {
  EditsIdRoute: EditsIdRoute,
  EditsIndexRoute: EditsIndexRoute,
}

const EditsRouteWithChildren = EditsRoute._addFileChildren(EditsRouteChildren)

interface ShopperRouteChildren {
  ShopperNewRoute: typeof ShopperNewRoute
  ShopperIndexRoute: typeof ShopperIndexRoute
}

const ShopperRouteChildren: ShopperRouteChildren = {
  ShopperNewRoute: ShopperNewRoute,
  ShopperIndexRoute: ShopperIndexRoute,
}

const ShopperRouteWithChildren =
  ShopperRoute._addFileChildren(ShopperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  EditsRoute: EditsRouteWithChildren,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  ShopperRoute: ShopperRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
